/**
 * useCase
 * change = new Change(type=NODE.CHANGE, )
 * type = "NODE_CHANGE"
 *
*/

export const NODE = {
  CHANGE: "NODE_CHANGE",
  ANIMATIONS: {
    NODE_SWAP: "NODE_SWAP",
    NODE_POSITION_CHANGE: "NODE_POSITION_CHANGE",
    NODE_COLOR_CHANGE: "NODE_COLOR_CHANGE",
    NODE_SIZE_CHANGE: "NODE_SIZE_CHANGE",
  },
};

export const EDGE = {
  CHANGE: "EDGE_CHANGE",
  ANIMATIONS: {
    EDGE_COLOR_CHANGE: "COLOR_CHANGE",
    EDGE_WEIGHT_DISPLAY: "WEIGHT_DISPLAY",
    EDGE_WEIGHT_CHANGE: "EDGE_WEIGHT_CHANGE",
  },
};
